[tool.poetry]
name = "pynotionclient"
version = "0.0.9-dev1"
description = "Python wrapper for Notion API"
authors = ["Vetrichelvan <pythonhub.py@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["notion", "api", "wrapper"]
packages = [{ include = "pynotionclient", from = "src" }]
repository = "https://github.com/pythonhubpy/PyNotion"
homepage = "https://github.com/pythonhubpy/PyNotion"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
pydantic = "^1.10.7"

[tool.poetry.group.development.dependencies]
python-dotenv = "^1.0.0"
pylint-quotes = "^0.2.3"
pytest-cov = "^4.0.0"
pytest = "^7.3.0"
pylint = "^2.17.2"
pre-commit = "^3.2.2"
mypy = "^1.2.0"
black = {extras = ["d"], version = "^23.3.0"}
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/pythonhubpy/PyNotion/issues"

[tools.pylint]
runtime-typing = true
